improve configuration
git-svn-id: https://svn.hepforge.org/applgridsvn/trunk@169 32d2155c-4299-4188-a341-1b4f4da92f88

diff --git a/appl_grid/configure b/appl_grid/configure
--- a/appl_grid/configure
+++ b/appl_grid/configure
@@ -871,7 +871,6 @@ FFLAGS
 ac_ct_F77
 LIBTOOL
 ROOTPATH
-LHAPDFPATH
 HOPPETPATH
 LIBOBJS
 LTLIBOBJS'
@@ -4785,7 +4784,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4788 "configure"' > conftest.$ac_ext
+  echo '#line 4787 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7044,11 +7043,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7047: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7046: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7051: \$? = $ac_status" >&5
+   echo "$as_me:7050: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7312,11 +7311,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7315: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7314: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7319: \$? = $ac_status" >&5
+   echo "$as_me:7318: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7416,11 +7415,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7419: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7418: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7423: \$? = $ac_status" >&5
+   echo "$as_me:7422: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9724,7 +9723,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9727 "configure"
+#line 9726 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9824,7 +9823,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9827 "configure"
+#line 9826 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12160,11 +12159,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12163: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12162: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12167: \$? = $ac_status" >&5
+   echo "$as_me:12166: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12264,11 +12263,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12267: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12266: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12271: \$? = $ac_status" >&5
+   echo "$as_me:12270: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13834,11 +13833,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13837: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13836: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13841: \$? = $ac_status" >&5
+   echo "$as_me:13840: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13938,11 +13937,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13941: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13940: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13945: \$? = $ac_status" >&5
+   echo "$as_me:13944: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16136,11 +16135,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16139: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16138: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16143: \$? = $ac_status" >&5
+   echo "$as_me:16142: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16404,11 +16403,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16407: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16406: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16411: \$? = $ac_status" >&5
+   echo "$as_me:16410: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16508,11 +16507,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16511: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16510: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16515: \$? = $ac_status" >&5
+   echo "$as_me:16514: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19591,6 +19590,9 @@ rm -f conftest.data
 #    FC="$F77"
 #  fi
 #fi
+
+
+
 # Extract the first word of "root", so it can be a program name with args.
 set dummy root; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -19633,50 +19635,27 @@ fi
 
 
 if test "$ROOTPATH" = "no"; then
+    { echo "$as_me:$LINENO: WARNING: ****************************************************" >&5
+echo "$as_me: WARNING: ****************************************************" >&2;}
+    { echo "$as_me:$LINENO: WARNING: " >&5
+echo "$as_me: WARNING: " >&2;}
     { echo "$as_me:$LINENO: WARNING: root was not found - needed for applgrid storage" >&5
 echo "$as_me: WARNING: root was not found - needed for applgrid storage" >&2;}
+    { echo "$as_me:$LINENO: WARNING: " >&5
+echo "$as_me: WARNING: " >&2;}
+    { echo "$as_me:$LINENO: WARNING: ****************************************************" >&5
+echo "$as_me: WARNING: ****************************************************" >&2;}
+else
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_CERNROOT 1
+_ACEOF
+
 fi
 
-# lhapdf isn't technically needed but leav it in anyhow
-# Extract the first word of "lhapdf-config", so it can be a program name with args.
-set dummy lhapdf-config; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_LHAPDFPATH+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $LHAPDFPATH in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_LHAPDFPATH="$LHAPDFPATH" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_LHAPDFPATH="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  test -z "$ac_cv_path_LHAPDFPATH" && ac_cv_path_LHAPDFPATH="no"
-  ;;
-esac
-fi
-LHAPDFPATH=$ac_cv_path_LHAPDFPATH
-if test -n "$LHAPDFPATH"; then
-  { echo "$as_me:$LINENO: result: $LHAPDFPATH" >&5
-echo "${ECHO_T}$LHAPDFPATH" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
+# lhapdf isn't technically needed
+# AH_TEMPLATE([HAVE_LHAPDF],[Define 1 if lhapdf is installed])
+# AC_PATH_PROG(LHAPDFPATH,lhapdf-config,no)
 
 
 
@@ -19722,11 +19701,24 @@ fi
 
 
 if test "$HOPPETPATH" = "no"; then
-    { echo "$as_me:$LINENO: WARNING: HOPPET was not found - needed for arbitrary applgrid scale evolution" >&5
-echo "$as_me: WARNING: HOPPET was not found - needed for arbitrary applgrid scale evolution" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ********************************************************************" >&5
+echo "$as_me: WARNING: ********************************************************************" >&2;}
+    { echo "$as_me:$LINENO: WARNING: " >&5
+echo "$as_me: WARNING: " >&2;}
+    { echo "$as_me:$LINENO: WARNING:    HOPPET was not found - you will not be able to arbirarily" >&5
+echo "$as_me: WARNING:    HOPPET was not found - you will not be able to arbirarily" >&2;}
+    { echo "$as_me:$LINENO: WARNING:    change the factorisation scale in the convolution" >&5
+echo "$as_me: WARNING:    change the factorisation scale in the convolution" >&2;}
+    { echo "$as_me:$LINENO: WARNING: " >&5
+echo "$as_me: WARNING: " >&2;}
+    { echo "$as_me:$LINENO: WARNING: ********************************************************************" >&5
+echo "$as_me: WARNING: ********************************************************************" >&2;}
 else
-    CPPFLAGS+=" -DHOPPET "
-    CXXFLAGS+=" -DHOPPET "
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_HOPPET 1
+_ACEOF
+
 fi
 
 
@@ -20531,13 +20523,12 @@ FFLAGS!$FFLAGS$ac_delim
 ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
 ROOTPATH!$ROOTPATH$ac_delim
-LHAPDFPATH!$LHAPDFPATH$ac_delim
 HOPPETPATH!$HOPPETPATH$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 9; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 8; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
